// Auto-generated by `npm run build-data` from the Whisper transcript.
// Until you run that script, these are placeholder values based on the
// silence-detection pass from IMG_0345_analysis.md.

export const VIDEO_FILE = "IMG_0345.mp4";
export const FPS = 30;
export const SOURCE_WIDTH = 1080;
export const SOURCE_HEIGHT = 1920;

// Segments to KEEP, in seconds, in the ORIGINAL video's timeline.
// The gaps between these ranges (dead air / silences) get cut out.
export const SPEECH_SEGMENTS: Array<{ start: number; end: number }> = [
  { start: 0, end: 4.3 },
  { start: 5.53, end: 14.06 },
  { start: 15.07, end: 17.87 },
  { start: 18.51, end: 21.02 },
  { start: 21.82, end: 24.55 },
  { start: 25.21, end: 26.91 },
  { start: 28.37, end: 34.35 },
  { start: 35.02, end: 37.11 },
];

// Captions, in seconds, in the ORIGINAL video's timeline.
// Replace by running `npm run build-data` against your Whisper JSON output.
export const CAPTIONS: Array<{ start: number; end: number; text: string }> = [
  { start: 0, end: 4.3, text: "(run build-data to fill in real captions)" },
];

// Color grade applied to every frame (CSS filter syntax).
export const COLOR_GRADE_FILTER =
  "brightness(1.08) contrast(1.12) saturate(1.18) sepia(0.04)";
