// Auto-generated by scripts/build-split-screen.js
// Run that script with the paths to your main video and the two overlay
// clips and it will fill in real durations/resolution and copy the files
// into public/.

export const MAIN_VIDEO = "main.mp4";
export const FPS = 30;
export const WIDTH = 1080;
export const HEIGHT = 1920;

// Total length of the composition (= main video duration), in seconds.
export const MAIN_DURATION = 60;

// Each overlay splits the screen (top = main video, bottom = overlay clip)
// starting at `mainStart` seconds into the main video, for `duration` seconds.
export const OVERLAYS: Array<{
  file: string;
  mainStart: number;
  duration: number;
}> = [
  { file: "overlay1.mp4", mainStart: 19.23, duration: 5 },
  { file: "overlay2.mp4", mainStart: 54.1, duration: 5 },
];
